### ISSUE TITLE
Some settings keep resetting to default

### ISSUE THREAD

**Issue by Triangularity** [Miodec/monkey-type#41] opened 2020-05-19 17:26 UTC
I've set "smooth caret" to off, and "live wpm" to on, but one or both reset themselves back to default on either browser restart or reboot.

"live wpm" seems to be consistently going back to default on browser restart.
"smooth caret" goes back to default more inconsistently.
The theme setting always stays where I selected.

This behavior occurs both when logged in and when not logged in.

**Comment by Miodec** [comment] 2020-05-19 18:00
Interesting. All user config is saved the moment it is changed - including smooth caret and live wpm. Ill have to think about what could be the issue

**Comment by Miodec** [comment] 2020-05-19 18:17
What browser are you using? Are you changing these settings through the settings page or command line. Do you have any steps that can reproduce this behaviour all the time?

**Comment by Triangularity** [comment] 2020-05-20 12:12
This was very strange so I experimented a bit on two different computers, and found this:

Windows + Vivaldi browser (chrome engine): 
-Reloading the page defaults the "live wpm" setting
-Smooth caret randomly defaults after a while, haven't been able to reproduce on purpose (once a reboot triggered it but not later)

Linux + Firefox:
-Closing and re-opening the browser 1st time defaults the "live wpm" setting
-Closing and re-opening the browser 2nd time defaults the "smooth caret" setting


However, this also happens:
Linux + Firefox:
-Reloading the page defaults the "live wpm" setting
-Closing and re-opening the browser any number of times after reloading the page had no effect on "smooth caret" setting

No other settings are affected

Steps to reproduce:
-open browser and go to monkeytype
-change all settings away from default
-reload page - or restart browser
-go to settings page to verify settings

**Comment by Miodec** [comment] 2020-05-20 15:25
Okay, i found that the livewpm setting would not be saved when changed through the settings page. Fixed in e66760cd4d4e4d2d42e664270f6a5cda5c64eb4c.

But i cant reproduce the smooth caret setting resetting.

**Comment by Triangularity** [comment] 2020-05-20 18:09
I had a little look at loadConfigFromCookie() in public/js/userconfig.js and it seems there is a call to every setter except there is no setSmoothCaret(newConfig.smoothCaret)
Could that be the problem?

(I'm just shooting in the dark here, so I hope you'll forgive me if I'm way off)

**Comment by Miodec** [comment] 2020-05-20 18:30
It doesnt really matter as the whole config is being overwritten there in the line `config = newConfig;`.

When you say that smooth caret has reset to default, are the buttons in the settings page showing the correct state? (if its off, is the off button highlighted)

If you say that it resets everytime you restart the browser, you could try to change the setting to off, then check the cookies and make sure its definitely false there, and then restart the browser. After that check the cookies again and make sure its still false. Then try to visit the website again.

Im trying to find out if youre experiencing problems with saving data to cookies or reading it.

**Comment by Triangularity** [comment] 2020-05-21 22:49
I haven't been able to trigger it for now, but good idea; I'll have a look at the cookie when/if the problem reappears and report back.

Also, thanks for fixing the "live wpm" part!

**Comment by Miodec** [comment] 2020-05-23 13:04
Since you havent been able to trigger it, i wll close it. If you encounter it again comment on this issue

**Comment by Triangularity** [comment] 2020-05-24 00:11
After a while of it looking like the problem was gone, the issue popped up again.

But now we're closer to seeing what is going on. This happens repeatably on both windows+vivaldi and linux+firefox.

1) Setting preference, liveWPM and smoothCaret work as set and the cookie looks like this:

{"theme":"serika_dark","showKeyTips":true,"showLiveWpm":true,"smoothCaret":false,"quickTab":true,"punctuation":false,"words":50,"time":30,"mode":"words","language":"english","fontSize":1}

2) Restarting browser, liveWPM and smoothCaret work as previously set and the cookie looks like this:
(Note that the problem occurs here, even though the functionality looks ok)

{"theme":"serika_dark","showKeyTips":true,"showLiveWpm":false,"smoothCaret":true,"quickTab":true,"punctuation":false,"words":50,"time":30,"mode":"words","language":"english","fontSize":1}

3) Restarting the browser again liveWPM and smoothCaret no longer function as I set them and the cookie looks like this:
(Same as last one)
{"theme":"serika_dark","showKeyTips":true,"showLiveWpm":false,"smoothCaret":true,"quickTab":true,"punctuation":false,"words":50,"time":30,"mode":"words","language":"english","fontSize":1}

**Comment by Miodec** [comment] 2020-05-31 20:23
Finally fixed.

**Closed by Miodec** 2020-05-31 20:23 UTC
Labels: bug
