### ISSUE TITLE
French circumflex accents are not recognized 

### ISSUE THREAD

**Issue by jolefevre** [Miodec/monkey-type#216] opened 2020-07-29 07:44 UTC
I can’t find a way to pass words with a `^` — which is [pretty common in French](https://en.wikipedia.org/wiki/Circumflex_in_French). 

![CleanShot 2020-07-29 at 09 35 56](https://user-images.githubusercontent.com/7468027/88771215-35b00000-d17f-11ea-9794-cf3e54b36a11.png)

Is this example, the normal way would be to type `^` then `i`. But when I do this, it still results in a mistake in monkey type. :( Am I missing something? I’m using AZERTY. 

Thanks for the great tool! 🙏

**Comment by Miodec** [comment] 2020-07-29 22:24
Known issue, duplicate of #36

**Closed by Miodec** 2020-07-29 22:24 UTC

**Comment by jolefevre** [comment] 2020-07-30 06:40
Oops, sorry for the duplicate!
