### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by tzanismad** [Miodec/monkey-type#94] opened 2020-05-29 02:15 UTC
After running `firebase serve --only hosting`, when i type the http://localhost:5000/ into my browser the page appears broken as such.
![image](https://user-images.githubusercontent.com/49292615/83213671-a1afc100-a15a-11ea-8d91-d8e61cec9a5a.png)
Is there a way to fix this?

**Comment by bhomie** [comment] 2020-05-29 02:17
This is not a bug, you need to compile the SCSS file.

**Comment by Miodec** [comment] 2020-05-29 16:07
Yeap, depending on your code editor of your choice there are plenty of extension for sass compilation. If you are using VSCode i recommend `Live Sass Compiler`. Closing

**Closed by Miodec** 2020-05-29 16:07 UTC
